# Cursor style
[cursor.style]
shape = "block"

[scrolling]
history = 10000

# Font settings
[font]
size = 11
[font.bold]
# family = "Mononoki Nerd Font"
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
# family = "Mononoki Nerd Font"
family = "Hack Nerd Font" 
style = "Italic"

[font.normal]
# family = "Mononoki Nerd Font" 
family = "Hack Nerd Font"
style = "Regular"

# Window settings
[window]
decorations = "full"
opacity = 0.9
padding = { x = 4, y = 4}

# ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#000000"
foreground = "#c5c9c5"

[colors.normal]
black   = "#0d0c0c"
red     = "#c4746e"
green   = "#8a9a7b"
yellow  = "#c4b28a"
blue    = "#8ba4b0"
magenta = "#a292a3"
cyan    = "#8ea4a2"
white   = "#c8c093"

[colors.bright]
black   = "#a6a69c"
red     = "#e46876"
green   = "#87a987"
yellow  = "#e6c384"
blue    = "#7fb4ca"
magenta = "#938aa9"
cyan    = "#7aa89f"
white   = "#c5c9c5"

[colors.selection]
text = "#c5c9c5"
background = "#2d4f67"

[colors.cursor]
text = "#181616"
cursor = "#c8c093"

[colors.vi_mode_cursor]
text = "#181616"
cursor = "#c8c093"

[colors.search.matches]
foreground = "#181616"
background = "#c5c9c5"

[colors.search.focused_match]
foreground = "#181616"
background = "#e6c384"

[colors.hints.start]
foreground = "#181616"
background = "#c4b28a"

[colors.hints.end]
foreground = "#181616"
background = "#a292a3"

[colors.footer_bar]
foreground = "#c5c9c5"
background = "#0d0c0c"
