# Cursor style
[cursor.style]
shape = "block"

[scrolling]
history = 10000

# Font settings
[font]
size = 10.5
[font.bold]
family = "Mononoki Nerd Font"
# family = "Cascadia Code"
style = "Bold"

[font.italic]
family = "Mononoki Nerd Font"
# family = "Cascadia Code" 
style = "Italic"

[font.normal]
family = "Mononoki Nerd Font" 
# family = "Cascadia Code NF"
style = "Regular"

# Window settings
[window]
decorations = "full"
opacity = 0.92
padding = { x = 4, y = 4}

# Colors (Gruvbox dark)

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ebdbb2'
