# Cursor style
[cursor.style]
shape = "block"

[scrolling]
history = 10000

# Font settings
[font]
size = 10.5
[font.bold]
# family = "Mononoki Nerd Font"
family = "Liberation Mono"
style = "Bold"

[font.italic]
# family = "Mononoki Nerd Font"
family = "Liberation Mono" 
style = "Italic"

[font.normal]
# family = "Mononoki Nerd Font" 
family = "Liberation Mono"
style = "Regular"

# Window settings
[window]
decorations = "full"
opacity = 0.95
padding = { x = 4, y = 4}

# ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#000000"
foreground = "#d4be98"

# [colors.normal]
# black   = "#111111"
# red     = "#ea6962"
# green   = "#a9b665"
# yellow  = "#d8a657"
# blue    = "#7daea3"
# magenta = "#d3869b"
# cyan    = "#89b482"
# white   = "#d4be98"
#
# [colors.bright]
# black   = "#504945"
# red     = "#ea6962"
# green   = "#a9b665"
# yellow  = "#d8a657"
# blue    = "#7daea3"
# magenta = "#d3869b"
# cyan    = "#89b482"
# white   = "#ebdbb2"
#
# [colors.selection]
# text = "#d4be98"
# background = "#3c3836"
#
# [colors.cursor]
# text = "#1d2021"
# cursor = "#d4be98"
