[colors]
background = #000000
foreground = #EBDBB2
background-alt = #282828

alert          = #ea6962
red            = #fb4934
orange         = #fe8019
yellow         = #fabd2f
green          = #b8bb26
aqua           = #8ec07c
sky            = #83a598
purple         = #d3869b

disabled       = #3c3836
dim            = #504945
grey           = #3c3836

[bar/bar]
underline-size = 2
override-redirect = false
wm-restack = i3
width = 100%
height = 17pt
offset-x = 10%
offset-y = 2%
radius = 0
fixed-center = true 
bottom = false


background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0

padding-left = 0
padding-right = 1
module-margin = 1

; separator = "|"
; separator-foreground = ${colors.disabled}

font-0 = "FiraMono Nerd Font:size=9.5;2"

modules-left =  i3 
modules-center = 
modules-right = pulseaudio memory cpu battery time 

cursor-click = pointer
cursor-scroll = ns-resize

tray-position = none 
tray-padding = 2
tray-maxsize = 11
tray-scale = 1.0
tray-offset-x = 0
tray-offset-y = 0
enable-ipc = true


; This module is not active by default (to enable it, add it to one of the
; modules-* list above).
; Please note that only a single tray can exist at any time. If you launch
; multiple bars with this module, only a single one will show it, the others
; will produce a warning. Which bar gets the module is timing dependent and can
; be quite random.
; For more information, see the documentation page for this module:
; https://polybar.readthedocs.io/en/stable/user/modules/tray.html
[module/systray]
type = internal/tray
tray-padding = 2px
tray-size = 12
tray-spacing = 4px

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = false
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true

format = <label-state> <label-mode>

label-focused =  %name% 

label-focused-foreground = ${colors.foreground}
label-focused-padding = 1

#label-unfocused = %icon%
label-unfocused = %name%
label-unfocused-foreground = #6f6f6f
label-unfocused-padding = 1

label-visible = %name%
label-visible-padding = 1

label-occupied = %name%
label-occupied-foreground = ${colors.blue}
label-occupied-padding = 1

label-empty = %name%
label-empty-padding = 1

label-urgent = %name%
label-urgent-foreground = ${colors.alert}
#label-urgent-background = #550000
label-urgent-padding = 1

[module/xworkspaces]
type = internal/xworkspaces

label-active = %icon%
label-active-foreground = #d3b17d
label-active-background = ${colors.background-alt}
#label-active-underline= ${colors.green}
label-active-padding = 1
label-occupied = %name%
label-occupied-background = ${colors.background}
label-occupied-foreground = ${colors.cyan}
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1


label-empty = %name%
label-empty-foreground = ${colors.foreground}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:20:...%
format = "<label>"
label-foreground = #e5e9f0
label-padding = 0


[module/filesystem]
type = internal/fs
interval = 1.5

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
label-volume = "%percentage%%"
format-volume = "<label-volume>"
format-volume-prefix-foreground = ${colors.green}
format-volume-padding = 0
label-muted = " "
label-muted-foreground = ${colors.dim}


[module/memory]
type = internal/memory
interval = 1
format-prefix =  "RAM "
format-prefix-foreground = ${colors.red}
label = "%percentage_used%%"
label-padding = 0

[module/cpu]
type = internal/cpu
interval = 1
format-prefix = "CPU "
format-prefix-foreground = ${colors.sky}
label = "%percentage:2%%"
label-padding = 0

[network-base]
type = internal/network
interval = 5
format-connected = " "  
format-disconnected = "󰖪 " 
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

; Click actions
click-left = nm-connection-editor &
click-right = rofi -show network
[module/wlan]
inherit = network-base
interface-type = wireless
format-prefix = "" 
label-connected = ""
click-left = ~/scripts/wifi-menu.sh

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/time]
type = internal/date
interval = 1
time = "%d-%m-%y %H:%M"
format = <label>
format-foreground = ${colors.purple}
label = "%time%"
label-padding = 0

[module/date]
type = internal/date
interval = 1
date = %Y %B %d, %A
label = " %date% "

[module/songs]
type = custom/script
exec = ~/scripts/musicplaying.sh
click-left = ~/scripts/musicplaying.sh toggle
click-right = ~/.config/polybar/scripts/musicplaying.sh next
scroll-down = ~/.config/polybar/scripts/musicplaying.sh prev
interval = 1


[module/upt]
type = custom/script
interval = 120
format-prefix = " "
format-prefix-foreground = ${colors.sky-blue}
exec = ~/scripts/uptime.sh

[module/pomodoro]
type = custom/script
exec = ~/scripts/pomodoro.sh
interval = 1
click-left = ~/scripts/pomodoro.sh --start
click-right = ~/scripts/pomodoro.sh --stop



[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT0
adapter = ADP1
poll-interval = 5
time-format = %H:%M
#ramp-capacity-foreground = ${colors.green}
#animation-charging-foreground = ${colors.red}
format-charging = CHR <label-charging>
format-discharging = BAT <label-discharging>
label-charging = %percentage%%
label-discharging =  %percentage%%
label-full = Fully charged
label-low = BATTERY LOW
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
bar-capacity-width = 10
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
animation-discharging-framerate = 500
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200
label-full-padding = 0
format-charging-padding = 0
format-discharging-padding = 0

[module/wifi]
type = custom/script
exec = ~/scripts/wifi-status.sh
interval = 5
click-left = ~/scripts/wifi-menu.sh
; format-prefix = ""

[settings]
throttle-input-for = 0
throttle-output = 0
throttle-output-for = 0
; No compositing (he does not use picom)
compositing-background = none
compositing-foreground = none
compositing-overline = none
compositing-underline = none
compositing-border = none
; No pseudo-transparency
pseudo-transparency = false

